### ISSUE TITLE
reason oauthtoken is empty?

### ISSUE THREAD

**Issue by Freundschaft** [EddyVerbruggen/cordova-plugin-googleplus#100]
I got everything working now, the only last step is to get the oauthtoken to send it to my server endpoint in order to log in there. Unfortunately after login its empty. What could be the reason for this? Maybe some wrong configuration?

Cheers

**Comment by sloot14** [comment]
I have the same problem

**Comment by rdrg** [comment]
Hi guys, 

I have this issue on IOS, too. And if you look at the source code of IOS somewhere around line 245:
```
NSString *email = user.profile.email;
        NSString *token = user.authentication.idToken;
        NSString *accessToken = user.authentication.accessToken;
        NSString *userId = user.userID;
        NSString *serverAuthCode = user.serverAuthCode != nil ? user.serverAuthCode : @"";
//        GTLPlusPerson *person = [GPPSignIn sharedInstance].googlePlusUser;
        NSDictionary *result = @{
                       @"email"       : email,
                       @"idToken"     : token,
                       @"oauthToken"  : serverAuthCode,
                       @"userId"      : userId,
                       @"displayName" : user.profile.name ?: [NSNull null]/*,
                       @"gender"      : person.gender ?: [NSNull null],
                       @"imageUrl"    : (person.image != nil && person.image.url != nil) ? person.image.url : [NSNull null],
                       @"givenName"   : (person.name != nil && person.name.givenName != nil) ? person.name.givenName : [NSNull null],
                       @"middleName"  : (person.name != nil && person.name.middleName != nil) ? person.name.middleName : [NSNull null],
                       @"familyName"  : (person.name != nil && person.name.familyName != nil) ? person.name.familyName : [NSNull null],
                       @"ageRangeMin" : person.ageRange && person.ageRange.min ? person.ageRange.min : [NSNull null],
                       @"ageRangeMax" : person.ageRange && person.ageRange.max ? person.ageRange.max : [NSNull null],
                       @"birthday"    : person.birthday ?: [NSNull null]*/
                       };
//        }
```
you can see that the accessToken is not being assigned to the oauthToken var in the dict it's forwarding to cordova. Don't know what serverAuthCode is, but it seems to be empty. What I did is change  
```
@"oauthToken"  : serverAuthCode,
```
to
```
@"oauthToken"  : accessToken,
```
and now I get the oauthToken as expected. A bunch of other stuff got uncommented, as you can see above, and I don't receive the image neither. I guess that's because Eddy is changing the sign in  implementation from gplus to the more generic "google sign in" (which is great). I don't know if it's possible to get an image (and the other profile vars) directly from this implementation, but you can get them calling something like:
```
$http.get('https://www.googleapis.com/oauth2/v1/userinfo?alt=json&access_token='+data.oauthToken)
.then(...)
```

best,

rodrigo

**Comment by EddyVerbruggen** [comment]
@rdrg Interestingly this has just been fixed by a PR earlier today: https://github.com/EddyVerbruggen/cordova-plugin-googleplus/blob/master/src/ios/GooglePlus.m#L250

**Comment by rdrg** [comment]
great! Thanks

**Comment by jkachi** [comment]
@EddyVerbruggen 

I'm still experiencing this issue, in the PR I can see the accessToken being assigned to @"accessToken" , but shouldn't be assigned to @"oauthToken as @rdrg said in his previous comment?

Thanks

**Comment by henritoivar** [comment]
Having the same issue. on android i could get the oauthtoken but not on ios.

**Comment by phw** [comment]
> 'm still experiencing this issue, in the PR I can see the accessToken being assigned to @"accessToken" , but shouldn't be assigned to @"oauthToken as @rdrg said in his previous comment?

No, the code as it is correct. accessToken is the token you can use in your client, oauthToken (= serverAuthCode) is the code you can send to the server. It is actually a one-time-token the server can exchange for a proper access and refresh token.

Having said this, I too experienced the same issue of an empty oauthToken, despite the login asking me for offline access. It is working now, but I am not entirely sure why. What I did is setup all the tokens in the [Google Developer Console](https://console.developers.google.com/) again. Maybe check your setup if it is similar to this:

1. I added the API key and client ID for my app using [this Wizard](https://developers.google.com/mobile/add?platform=ios&cntapi=signin&cnturl=https:%2F%2Fdevelopers.google.com%2Fidentity%2Fsign-in%2Fios%2Fsign-in%3Fconfigured%3Dtrue&cntlbl=Continue%20Adding%20Sign-In). Make sure you use the correct bundle ID for your app. When I looked into the Google Developer Console it had added both an iOS API Key and a iOS oAuth 2.0 client ID.
2. I set the reversed version of that client ID (it is labeled iOS URL scheme in the Developer Console) the `REVERSED_CLIENT_ID` parameter of the plugin
3. In the Google Developer Console I added a second oAuth 2.0 client ID of type "Web Application". It is important to set this client ID inside the same Developer Console project! That client ID needs to be used as the `webApiKey` when calling `window.plugins.googleplus.login`:

    ```JavaScript
    var options = {
        webApiKey: WEB_OAUTH_CLIENT_ID
    };
    window.plugins.googleplus.login(options, function(result) {
        console.log(result.oauthToken);
        // Send this token to your server
    });
   ```
4. Now send `result.oauthToken` to the server. The server must exchange this one-time token for a proper access token using the process described in https://developers.google.com/identity/sign-in/web/server-side-flow . It is important that the server uses the "Web Application" credentials added in step 3 above.

See also:
* https://developers.google.com/identity/sign-in/ios/offline-access
* https://developers.google.com/identity/protocols/CrossClientAuth
* Also see my answer to #80 for Android

**Comment by vdimitrieski** [comment]
Hi all, 

I tried all of the aforementioned solutions, including the one from @phw, but with no success. I get oauthtoken on the android device, but I cannot get it on iOS (where I get everything else except of this token). 

Any more toughts on how to solve this? Or just completely to switch off google sign in for iOS...

Thanks

**Comment by revolter** [comment]
Same.

**Comment by marcin-piela** [comment]
Same, but on android (only userID). On iOS is fine.

**Comment by velickym** [comment]
I' having similar issue where serverAuthCode is always empty string (all other fields in the response object are populated including idToken) - https://stackoverflow.com/questions/45774169/serverauthcode-from-response-is-empty-ios-cordova-plugin-googleplus
