### ISSUE TITLE
Incompatibility with cordova-plugin-facebook4

### ISSUE THREAD

**Issue by tomasbedrich** [EddyVerbruggen/cordova-plugin-googleplus#213]
For description plese see the issue for cordova-plugin-facebook4: https://github.com/jeduan/cordova-plugin-facebook4/issues/193.

**Comment by leonardobazico** [comment]
+1

**Comment by ezazwar1** [comment]
+1

**Comment by ezazwar1** [comment]
@EddyVerbruggen  any suggessions

**Comment by vivekpd15** [comment]
+1

**Comment by ezazwar1** [comment]
-canOpenURL: failed for URL: "fbauth://authorize?sdk_version=3.21.1&legacy_override=v2.2&response_type=token%2Csigned_request&display=touch&scope=email%2Cpublic_profile&state=%7B%22is_open_session%22%3Atrue%2C%22is_active_session%22%3Atrue%2C%220_auth_logger_id%22%3A%22D613D006-5686-4E59-8808-D5E0781A20A8%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22fb_application_web_auth%22%7D&e2e=%7B%22init%22%3A1460572452879%7D&redirect_uri=fbconnect%3A%2F%2Fsuccess&return_scopes=true&client_id=547604765422561&sdk=ios" - error: "(null)"
2016-04-14 00:04:12.886 KashmirNow[50057:533777] THREAD WARNING: ['FacebookConnectPlugin'] took '11.605225' ms. Plugin should use a background thread.
 


Error thrown in facebook plugin

**Comment by EddyVerbruggen** [comment]
Did you [whitelist the `fbauth` scheme?](https://github.com/jeduan/cordova-plugin-facebook4/issues/3)

**Comment by ezazwar1** [comment]
yes i did

it was working fine until i added the googleplus plugin 

Now only googleplus plugin is working while the facebook plugin is not working anymore

**Comment by EddyVerbruggen** [comment]
Found the problem in a recently merged PR. I've just pushed a change to fix compatibility issues with the Fb plugin.

Note that `canOpenURL: failed for URL: "fbauth2:/` is merely a symptom of something being wrong. It might as well be your Facebook app ID is incorrect.

Please update from the master branch and you should be good to go.

**Comment by ezazwar1** [comment]
@EddyVerbruggen  the Facebook app Id is correct 
Let me check tonight and i will let you know whether the facebook plugin is working or not

**Comment by ezazwar1** [comment]
Hey @EddyVerbruggen  issue seems to be fixed but there is still a problem that needs to be checked

Autologin of facebook plugin doesnt work 
For google+ it works fine

Error logged 



-canOpenURL: failed for URL: "fbauth://authorize?state=%7B%22is_open_session%22%3Atrue%2C%22is_active_session%22%3Atrue%2C%220_auth_logger_id%22%3A%2254ED729E-9286-47A5-B884-E955633EE106%22%2C%22com.facebook.sdk_client_state%22%3Atrue%2C%223_method%22%3A%22fb_application_web_auth%22%7D&return_scopes=true&response_type=token%2Csigned_request&display=touch&e2e=%7B%22init%22%3A1460651850587%7D&sdk_version=3.21.1&auth_type=rerequest&scope=email%2Cpublic_profile&sdk=ios&redirect_uri=fbconnect%3A%2F%2Fsuccess&client_id=547604765422561&legacy_override=v2.2" - error: "(null)"


fbauth is already in my plist

Regards 
Ezaz

**Comment by EddyVerbruggen** [comment]
Hi, does auto-login of fb work without googleplus installed? If so, what's the code snippet I need to run to try it? Cheers!

**Comment by ezazwar1** [comment]
Yes it works fine if i remove the google plus plugin



document.addEventListener('deviceready', function() { 
  var cover;
  window.plugins.googleplus.trySilentLogin(
    {
      'offline': true // optional and required for Android only - if set to true the plugin will also return the OAuth access token, that can be used to sign in to some third party services that don't accept a Cross-client identity token (ex. Firebase)
    },
    function (obj) {
     var items = getCover.getCoverImage(obj.userId).then(function(data){
      cover = data.cover.coverPhoto.url;
       LoginService.setUser({    
        authResponse: obj.oauthToken,
        userID: obj.userId,
        name: obj.displayName,
        email: obj.email,
        cover: cover,
        picture : obj.imageUrl
            });
    });

      $state.go('tab.dash');
    });
    facebookConnectPlugin.getLoginStatus(function(success){
     if(success.status === 'connected'){
        var user = LoginService.getUser('facebook');
        if(!user.userID)
        {
          getFacebookProfileInfo(success.authResponse)
          .then(function(profileInfo) {
            LoginService.setUser({
        authResponse: authResponse,
        userID: profileInfo.id,
        name: profileInfo.name,
        email: profileInfo.email,
        cover: profileInfo.cover.source,
        picture : profileInfo.picture.data.url
            });
            $state.go('tab.dash');
          }, function(fail){
            console.log('profile info fail', fail);
          });
        }else{
          $state.go('tab.dash');
        }
     }
    });
   });

**Comment by ezazwar1** [comment]
i check if the google or facebook is logged in previously then i $state them to another view

**Comment by EddyVerbruggen** [comment]
I've just tried this with a fresh project: sign in to Fb and G, then kill the app, start again, and on deviceready execute your code: both Fb and G log in successfully..

**Comment by ezazwar1** [comment]
i tried the same and its working on device but is not working on simulator 

Anyways i will test more and let you know if i have some issues with same  :+1: :100: 

btw i want your suggession about which facebook plugin should i use the version 4 one or wizcorp one 


Regards 
Ezaz

**Comment by EddyVerbruggen** [comment]
Funny - it worked on my simulator as well (had to remove the app first though), but glad it's working on your device!

I don't use the Fb personally, perhaps ask in the phonegap Slack group?

**Comment by ezazwar1** [comment]
Thanks man you are a genius 


I was looking forward of making some Plugins but need some assistance where to start from

**Comment by vivekpd15** [comment]
Thanks Eddy. It is resolved now.
