### ISSUE TITLE
The operation couldn’t be completed. (com.google.HTTPStatus error 400.)

### ISSUE THREAD

**Issue by MarcGodard** [EddyVerbruggen/cordova-plugin-googleplus#39]
I get this error?

```
The operation couldn’t be completed. (com.google.HTTPStatus error 400.)
```

What am I missing?

**Comment by teknologist** [comment]
Getting the same error here

**Comment by teknologist** [comment]
@MarcGodard  did you solve this ? Many thanks!

**Comment by teknologist** [comment]
@MarcGodard  By the way, I am only getting this on iOS. Android works perfectly.

**Comment by bpevangelista** [comment]
I'm also getting the same error, this happens if I have Google+ installed otherwise the web version works fine.

**Comment by battumurd** [comment]
check your ios app Bundle identifier

**Comment by tilast** [comment]
hey guys any updates on this issue?

**Comment by romainPellerin** [comment]
I got the same issue, please fix, unable to integrate this plugin for iOS...

**Comment by romainPellerin** [comment]
This issue is solved when installing the lib from this git repo instead of Cordova official one's:
```
cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=x
```
Thanks @EddyVerbruggen for the work!

**Comment by Birdiboy** [comment]
I have installed the plugin in proper manner from as: cordova plugin add https://github.com/EddyVerbruggen/cordova-plugin-googleplus --variable REVERSED_CLIENT_ID=com.googleusercontent.apps.724689183917-7f7e81jesqngbkg7mqkhj7115elam9at

But Still I am facing this issue. Also the bundle id is same as mentioned in google developer console project. Please help me and tell what's the issue exactly.

**Comment by YaroslavG** [comment]
Birdiboy, 
I have the same problem, do you find solution?

**Comment by Vasanth19** [comment]
+1, tried getting from github, still the same issue on ios9

**Comment by Vasanth19** [comment]
**Resolved it !** followed the below steps
1. Create the ios client id in google developer console
2. Create the web client id and make sure to enter the call back url as http://localhost/callback
3. get the url scheme for ios client id in google dev portal and use it for Reversed_Client_Id (* note: ios client id is used, not the web client id *)
4. In your code, send the web client id in the options while calling login method.

**Comment by tesnep** [comment]
@Vasanth19 what does step 3 mean? Do you mean specify url scheme as REVERSED_CLIENT_ID or specify ios client id as REVERSED_CLIENT_ID?

**Comment by niciejatomasz** [comment]
I'm still having the same error 400, I have generated keys as you wrote.

**Comment by Blank101** [comment]
I am also getting this error even after following all directions in this thread.

**Comment by Blank101** [comment]
Solved my issue. I was entering the webClientId parameter using the reversed web client id format instead of the normal web client id format.

**Comment by richardmarais** [comment]
What for mat must we use?

`yourclientid.apps.googleusercontent.com`

or 

`com.googleusercontent.apps.yourclientid`

1. In the code where you make the login call, i.e.  what should `webClientId` be?

```
            GooglePlus.login({
                'webClientId': webClientId,
                'offline': true
            }).then(googleData => {
```

2. For iOS, in `config.xml`:

    <plugin name="cordova-plugin-googleplus" spec="~5.1.1">
        <variable name="REVERSED_CLIENT_ID" value="com.googleusercontent.apps.yourclientid" />
    </plugin>

3. Anywhere else?

**Comment by alemak1** [comment]
I everyone, I've been working on a Navigation/Travel App here in Korea, and came upon the same error because I'm integrating a translation functionality into the app that requires calling the Google Translate API.  

The status code is 400, but there is still an error involved, which  means that something else is wrong in terms of your URL (i.e. you are missing parameters in your required URL, or you have to include more information in your request header).  

If you are, for example, calling using the completion handler for the GTMSFetcher object as show below, to make the problem more clear, remove any error handling code from beginning of the code, as show in the official docs, and debug the problem by parsing the JSON object and getting the JSON parsing error, as show below:

[fetcher beginFetchWithCompletionHandler:^(NSData *data, NSError *error) {
       
        // Parses the JSON response.
        NSError *jsonError = nil;
        id jsonDictionaryOrArray =
        [NSJSONSerialization JSONObjectWithData:data options:0 error:&jsonError];
        
        // JSON error.
        if (jsonError) {
            NSLog(@"JSON decoding error %@", jsonError);
            return;
        }
        
        // Success response!
        NSLog(@"Success: %@", jsonDictionaryOrArray);
    }];

In your debug console, you will get more specific information, such as this: 

Success: {
    error =     {
        code = 400;
        errors =         (
                        {
                domain = global;
                message = "Missing required field target";
                reason = badRequest;
            }
        );
        message = "Missing required field target";
        status = "INVALID_ARGUMENT";
    };
}

Strangely enough, when I used the URL with my API key included, I got this error: 

Success: {
    error =     {
        code = 403;
        errors =         (
                        {
                domain = global;
                message = "Requests from this ios client application <empty> are blocked.";
                reason = forbidden;
            }
        );
        message = "Requests from this ios client application <empty> are blocked.";
        status = "PERMISSION_DENIED";
    };
}

So now I just avoid including my API key in the URL and instead just set the bearer token in the request header. 

Hope that helps.

**Comment by kyleabens** [comment]
I'm still running into this issue.  I've set the ID's I've triple checked everything and I'm still getting this error in ionic.  I've also removed and re added the plugin.  Can't get past this one.

**Comment by nlasso** [comment]
I had the same issue using firebase. Try using instead of the webClientID from the **Google Developer Console** the one you create from **iOS Firebase App** in the correct order, that is: ```yourclientid.apps.googleusercontent.com``` They must match, if you are using **Firebase** you must use both of them from firebase.

**Comment by gersonmontenegro** [comment]
just as @richardmarais said, the key in iOS is use CLIENT_ID instead REVERSED_CLIEN_ID at the login beginning:
```
      const gplusUser = await this.gplus.login({
        'webClientId': 'CLIENT_ID extracted from GoogleService-Info.plist',
        'offline': true,
        'scopes': 'profile email'
      });

```
