### ISSUE TITLE
cordova 5.0 cli "version" problem

### ISSUE THREAD

**Issue by bau720123** [EddyVerbruggen/cordova-plugin-googleplus#56]
hi @EddyVerbruggen 
I am using cordova 5.0 cli
there is a new "version" problem
all detail at here
http://www.littlebau.com/cli/googleplus_cli.gif

**Comment by bau720123** [comment]
Phonegap Build (have the same problem)
what's wrong ?
http://www.littlebau.com/cli/googleplus_build.gif

**Comment by orthodoc** [comment]
I am getting the same problem.

Is it because the google-play-services plugin is [deprecated](https://github.com/MobileChromeApps/google-play-services)?

**Comment by EddyVerbruggen** [comment]
Hi, looks like the playservices dependency got a version bump (as well as deprecation).

After I've published a new version please you will be able to use this in config.xml for phonegap build (and ignore any deprecation warnings for now):

```xml
<gap:plugin name="nl.x-services.plugins.googleplus" source="plugins.cordova.io"/>
```

(I have plugman issues currently but will attempt again in a few hours and report back).

Thanks,
Eddy

**Comment by EddyVerbruggen** [comment]
OK, the update has been published, please try again.

**Comment by bau720123** [comment]
thanks @EddyVerbruggen 
PGB's problem solved when I use 1.1.2 version
but Cordova 5.0 cli problem still exist (but appear another error)
http://www.littlebau.com/cli/googleplus_cli2.gif

**Comment by EddyVerbruggen** [comment]
Thx. 

Perhaps you need to uninstall the old version first.

**Comment by bau720123** [comment]
I did it before
but the same...

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I rebuild a new project and re add the latest plugin
finally build android success
nut if I remove this plugin and re add again
it will show this warning message
is it normal or abnormal ?
http://www.littlebau.com/cli/googleplus_cli3.gif

**Comment by EddyVerbruggen** [comment]
Yeah see my deprecation comment above ;)

**Comment by bau720123** [comment]
hi @EddyVerbruggen 
I found that maybe a new version "com.google.play.services" at here
http://plugins.cordova.io/#/package/com.google.play.services

so...maybe install this first
cordova plugin add com.google.play.services
although I don't know if it got work...
