### ISSUE TITLE
Consent screen infinite loop (Cordova 9 - Android 9)

### ISSUE THREAD

**Issue by mirko77** [EddyVerbruggen/cordova-plugin-googleplus#659]
I built the demo Cordova app adding only:

```
{
webClientId: 'XXXYYYZZZ',
offline: true
},

```

The consent screen shows itself over and over after tapping on "Allow", it does not go past it.

cordova 9.0.0 (cordova-lib@9.0.1)
cordova-android 8.1.0
cordova-plugin-googleplus 8.2.0

Tested on Android 9

**Comment by mirko77** [comment]
Same issue down to plugin version 5.2.3

All good with 5.1.1, aside from the crash reports on Play Store, see #440

**Comment by zarelint** [comment]
Personally i did not use cordova 9 yet, there are some issues in the way of handling promises, If i were you I would do the compilation with cordova 8.1.0

`cordova platform add android@8.1.0  `

**Comment by mirko77** [comment]
> Personally i did not use cordova 9 yet, there are some issues in the way of handling promises, If i were you I would do the compilation with cordova 8.1.0
> 
> `cordova platform add android@8.1.0 `

Yes, I am using cordova-android 8.1.0

Cordova 9 is the CLI

**Comment by zarelint** [comment]
> > Personally i did not use cordova 9 yet, there are some issues in the way of handling promises, If i were you I would do the compilation with cordova 8.1.0
> > `cordova platform add android@8.1.0 `
> 
> Yes, I am using cordova-android 8.1.0
> 
> Cordova 9 is the CLI

I've corrected the commnet sorry

**Comment by mirko77** [comment]
Any updates?

I tried downgrading to cordova@8.1.2, plugin version 7.0.2 and still the same issue on Android 9

**Comment by grumpygary** [comment]
Same issue here (cordova 9, cordova 8.0.0).  I get the Google popup, but it errors out with code 10 (developer error).

When I upgraded to android 8.1.0 (did a full build), the googleplus plugin install said it failed, looking for Ruby 2.3 (I have 2.6 installed).  That said; it actually was installed, but I still get the error 10.  Perhaps this could provide a clue...

**Comment by grumpygary** [comment]
Update.

Updated cocoapods on Mac, fixed ruby issue.  Android version (using android 8.1.0) installed ok.  IOS reported the following error during install (cocoapods version: 1.8.4):

Installing "cordova-plugin-googleplus" for ios
Running command: pod install --verbose
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/me/dev/cordova in PATH, mode 040777

Failed to install 'cordova-plugin-googleplus': Error: pod: Command failed with exit code 31 Error output:
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/me/dev/cordova in PATH, mode 040777
    at ChildProcess.whenDone (/Users/me/dev/cordova/builds/app/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
pod: Command failed with exit code 31 Error output:
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/me/dev/cordova in PATH, mode 040777
----

I understand this is a permissions issue, but I have many plugins, and yours is the only one with this error.

When I tried building it in XCode, it reports that it can't find the <GoogleSignIn.h> file.

**Comment by grumpygary** [comment]
Another update...

Android:
-- still returning error code 10.

iOS:
1. My previous comment was edited after resolving the permissions issue.
2. The result of the error in the previous issue was that the GoogleSignIn pod was not installed.  I determined that it was due to duplicate ios pods (GoogleUtilities is also used by FireBase), and fixed by taking out the "pod GoogleUtilities" and rerunning the pod install.
3. IOS build succeeded, but app crashes
4. Removed googleplus plugin, app works again.

I suspect you'll need to update all your version references to get things working again on  iOS.  I guess I'll add Sign-In with Google at a later date.

**Comment by mirko77** [comment]
@grumpygary with cordova@8.1.2, plugin version 7.0.2, cordova-ios 4.5.5 it is all good on iOS

**Comment by grumpygary** [comment]
Yeah.  I've seen that.  The issue is that I need more recent versions of cordova-ios for other plugins.  Will keep trying... Thanks!

**Comment by ambr89** [comment]
@grumpygary do you have found a solution?

**Comment by govi2010** [comment]
@ambr89  did you found any solution ?

**Comment by faldunate** [comment]
I have the same problem here :/ some solution?

**Comment by govi2010** [comment]
@faldunate  No, We are waiting for a fix.

**Comment by madhu131313** [comment]
Let me know if anybody finds a solution. I see that server side google authentication might work.

**Comment by careduct** [comment]
Same error here. I've already updated all versions to the latest of: the plugin, cordova, play services. But still stuck on the infinite loop.
I've inspected the logcat but there are no error message there.
Did as well the network sniffing and I can see the sucessful answer from the google server. So, it looks like an issue in the play services that are not calling back the handler.

Any solution for this?

**Comment by mirko77** [comment]
The only solution for us is to use version 5.1.1 of the plugin

**Comment by careduct** [comment]
Finally found the issue, it is related with the @ionic-native/google-plus  wrapper of the plugin...
What we did to get it back working:

1. Remove the wrapper: npm uninstall --save @ionic-native/google-plus 
2. Remove all imports you may have and corresponding referencing: import { GooglePlus } from '@ionic-native/google-plus';
3. add directly the plugin calls via the windows var:
        declare var window: any;
        ...
        return window.plugins.googleplus.trySilentLogin({}, function(res) { ...

For the ones that used promises with the wrapper, be careful because the plugin uses callbacks.
Note: we have updated to the last version of the plugin ->8.5.0
